version: '2.1'
services:
  api:
    container_name: api
    image: markthub/server:latest
    ports:
      - "8080:8080"
    environment:
      - NGROK_URL=3333
  mysql:
    container_name: mysql
    image: mysql:5.6
    ports:
       - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=markthub
      - MYSQL_USER=markthub
      - MYSQL_PASSWORD=markthub